pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Checkout code from a Git repository
                git url: 'https://github.com/johntech123/Jenkins-Zero-To-Hero'
            }
        }
        
        stage('Build') {
            steps {
                // Placeholder for build command
                sh 'echo Building...'
            }
        }

        stage('Test') {
            steps {
                // Placeholder for test command
                sh 'echo Testing...'
            }
        }
    }

    post {
        always {
            // Clean up workspace after build
            cleanWs()
        }
        
        success {
            // Actions if the build is successful
            echo 'Build and tests succeeded!'
        }
        
        failure {
            // Actions if the build fails
            echo 'Build or tests failed.'
        }
    }
}

           
